import type { Metadata } from "next";
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";
import Navbar from "@/ui-components/layout/Navbar";
import QueryProvider from "@/providers/QueryProvider";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />

        <QueryProvider>
  {children}
</QueryProvider>
        <Toaster richColors position="top-right" />
      </body>
    </html>
  );
}