  #cloud-config
package_update: true
package_upgrade: true

packages:
  - git
  - curl
  - unzip
  - ca-certificates
  - apt-transport-https
  - software-properties-common

runcmd:

  # Enable Docker
  - curl -fsSL https://get.docker.com | sh
  
  # Enable Docker
  - systemctl enable docker
  - systemctl start docker

  # Install Docker Compose Plugin
  - curl -SL https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose

  # Allow Azure user to run Docker
  - usermod -aG docker azureuser


  # Deployment directory
  - mkdir -p /opt/formflow/deployment

  - chown -R azureuser:azureuser /opt/formflow

  - echo "FormFlow VM bootstrap completed."