name: Build, Push and Deploy

on:
  push:
    branches:
      - dev

permissions:
  contents: read

env:
  IMAGE_TAG: 1.0.3

jobs:

  ####################################################
  # BUILD + PUSH
  ####################################################

  docker:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      ####################################################
      # Backend
      ####################################################

      - name: Build Backend
        run: |
          docker build \
            -t kunzydev/formflow-backend:${IMAGE_TAG} \
            -f backend/Dockerfile \
            ./backend

      - name: Push Backend
        run: docker push kunzydev/formflow-backend:${IMAGE_TAG}

      ####################################################
      # Frontend
      ####################################################

      - name: Build Frontend
        run: |
          docker build \
            -t kunzydev/formflow-frontend:${IMAGE_TAG} \
            -f frontend/Dockerfile \
            ./frontend

      - name: Push Frontend
        run: docker push kunzydev/formflow-frontend:${IMAGE_TAG}

      ####################################################
      # Nginx
      ####################################################

      - name: Build Nginx
        run: |
          docker build \
            -t kunzydev/formflow-nginx:${IMAGE_TAG} \
            -f deployment/nginx/Dockerfile \
            ./deployment/nginx

      - name: Push Nginx
        run: docker push kunzydev/formflow-nginx:${IMAGE_TAG}

  ####################################################
  # DEPLOY: When VM is up and running
  ####################################################

  # deploy:

  #   needs: docker

  #   runs-on: ubuntu-latest

  #   steps:

  #     - name: Checkout Repository
  #       uses: actions/checkout@v4

  #     - name: Copy Compose Files to VM
  #       uses: appleboy/scp-action@v0.1.7
  #       with:
  #         host: ${{ secrets.AZURE_VM_IP }}
  #         username: ${{ secrets.AZURE_VM_USER }}
  #         key: ${{ secrets.AZURE_VM_SSH_KEY }}
  #         source: "deployment/docker-compose.prod.yml,deployment/.env.production"
  #         target: "~/formflow"

  #     - name: Deploy Containers
  #       uses: appleboy/ssh-action@v1.2.0
  #       with:
  #         host: ${{ secrets.AZURE_VM_IP }}
  #         username: ${{ secrets.AZURE_VM_USER }}
  #         key: ${{ secrets.AZURE_VM_SSH_KEY }}
  #         script: |

  #           cd ~/formflow/deployment

  #           docker compose \
  #             --env-file .env.production \
  #             -f docker-compose.prod.yml \
  #             pull

  #           docker compose \
  #             --env-file .env.production \
  #             -f docker-compose.prod.yml \
  #             up -d

  #           docker image prune -f